### PR TITLE
fix: improve full page forms to avoid using a modal

### LINKED ISSUE #724: Get forms out of FullPageModal
Right now, `consumer_form` is a LiveComponent. We render it inside of the `FullPageModal` component because:

* A full page modal is a nice UX pattern for displaying a form for create or edit: mentally, the user is still on the page where they clicked "Create/Edit"
* We don't want to display the sidenav when displaying a form.

This works mostly well - however, there are some quirks. Whenever a tooltip is closed, the window scrolls to the top of the FullPageModal - not desirable.

We either want to:

1. Determine why the scroll top behavior occurs - and fix it (we're using ShadCN Svelte).
2. Move `consumer_form` into a LiveView. Just redirect to a different path when rendering the form. It should still *feel* like a full-page modal, but it won't be.

### PR DESCRIPTION
**Pull request by davoclavo**
Improve rendering full page forms by removing the Modal/Dialog wrapper that was causing some quirks with some event handling.

Forms:
 - Sink
 - Database
 - HTTP endpoint
 - WAL Pipeline

Related additional improvements:
 - The new component name is changed from `FullPageModal` to `FullPageForm`
   - Simplified external props
 - Now we ask for confirmation on exit by default, instead of the opposite. It is still configurable via a prop if needed to override.
 - Replaced read only `Popovers` for `Tooltips`. Keep Popovers for cases where we need an additional input. This improves usability as information is shown on hover.
 - Fixed Message Group card on Sink form to be expanded by default
 - Improved rendering the horizontal scrollbar on `CodeWithCopy` blocks

Shoutout to @acco for the help figuring a robust solution!

Fixes #724

### CODE REVIEW

File: lib/sequin_web/live/wal_pipelines/form.ex [hunk 1]
```diff
@@ -30,10 +30,10 @@ defmodule SequinWeb.WalPipelinesLive.Form do
          |> assign(is_edit: is_edit)
          |> assign(show_errors?: false)
          |> assign(submit_error: nil)
-         |> assign_changeset(%{})}
+         |> assign_changeset(%{}), layout: {SequinWeb.Layouts, :app_no_sidenav}}
```
Comment (fazzone) [inline lib/sequin_web/live/wal_pipelines/form.ex:33]: can you write socket=... on another line above?

**Comment by fazzone** [comment]
The code changes are looking really good!  Loving the net-red diff!  However, trying to test this locally I noticed a weird issue with the test connection button of the create sink form - it looks like the popover is flashing into and out of existence very rapidly when it should be opened until dismissed?  Hard to explain - see the video: https://www.loom.com/share/1aeb311eb6904ad6ab3a2b781f9ee00f?sid=c3978947-4aea-4798-bc0e-e4aec57161cf

**Comment by davoclavo** [comment]
@fazzone thanks a lot for reporting that issue. Let me take a look at it and issue a fix

File: lib/sequin_web/live/wal_pipelines/form.ex (hunk 1 above)
Comment (davoclavo) [reply lib/sequin_web/live/wal_pipelines/form.ex:33]: @fazzone Sure! just to confirm, do you mean to make your suggested change in the render function instead?

```diff
--- a/lib/sequin_web/live/wal_pipelines/form.ex
+++ b/lib/sequin_web/live/wal_pipelines/form.ex
@@ -52,6 +52,8 @@ defmodule SequinWeb.WalPipelinesLive.Form do
     <div id="wal-pipeline-form">
       <.svelte
         name="wal_pipelines/Form"
+        socket={@socket}
         props={
           %{
             walPipeline: encode_wal_pipeline(assigns),
```

Also, would it make sense to add `ssr={false}` as well? I am still unsure of which components should be server side rendered and which ones don't, but I noticed that the databases/form.ex is also setting that property as well

**Comment by davoclavo** [comment]
@fazzone I just pushed a fix to the issue you reported. Thanks for reporting that bug! it was due to my change on the previous `<Popover.Trigger>` structure.

File: lib/sequin_web/live/wal_pipelines/form.ex (hunk 1 above)
Comment (davoclavo) [reply lib/sequin_web/live/wal_pipelines/form.ex:33]: Ohh I think I understand what you mean: to refactor the assignment to not have so many nested brackets/tuples.

```diff
--- a/lib/sequin_web/live/wal_pipelines/form.ex
+++ b/lib/sequin_web/live/wal_pipelines/form.ex
@@ -24,13 +24,15 @@ defmodule SequinWeb.WalPipelinesLive.Form do

     case fetch_or_build_wal_pipeline(socket, wal_pipeline_id) do
       {:ok, %WalPipeline{} = wal_pipeline} ->
-        {:ok,
-         socket
-         |> assign(wal_pipeline: wal_pipeline)
-         |> assign(is_edit: is_edit)
-         |> assign(show_errors?: false)
-         |> assign(submit_error: nil)
-         |> assign_changeset(%{}), layout: {SequinWeb.Layouts, :app_no_sidenav}}
+        socket =
+          socket
+          |> assign(wal_pipeline: wal_pipeline)
+          |> assign(is_edit: is_edit)
+          |> assign(show_errors?: false)
+          |> assign(submit_error: nil)
+          |> assign_changeset(%{}), layout: {SequinWeb.Layouts, :app_no_sidenav}
+
+        {:ok, socket}

```

Aside from that, do you happen to have context on the `socket={@socket}` and `ssr={false}` props I mentioned?

Comment (davoclavo) [reply lib/sequin_web/live/wal_pipelines/form.ex]: Done!

**Comment by acco** [comment]
This looks great! Awesome work here @davoclavo this has been bugging us for a while 🙏
